#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
# OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
# ------------------------------------------------------------------------------
# Name.......: anonymize_audit_log.py
# Author.....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
# Editor.....: Stefan Oehrli
# Date.......: 2026.05.28
# Version....: 0.2.0
# Purpose....: Pseudonymise sensitive values in spool files generated by
#              SQL audit queries so the contents can be shared for analysis
#              without exposing customer hostnames, users, schemas, or object
#              names. Column-aware: uses the heading line directly above each
#              SQL*Plus dashes line to decide which columns to extract.
# Notes......: Deterministic mapping - same input value always yields the
#              same pseudonym across runs (values sorted, numbered).
#              Existing mappings can be reloaded via --load-mapping for
#              incremental anonymisation across multiple log files.
#
#              Two-pass extraction:
#                1. Section-aware: parses "Show top unified audit events
#                   by <X>" blocks and harvests first-column values per
#                   category (userhost / dbusername / os_username / ...).
#                2. Pattern-based: scans the whole file for IPv4 addresses,
#                   FQDNs and email addresses.
#
#              Whitelist (NEVER anonymised):
#                - Oracle-supplied users/schemas (SYS, SYSTEM, AUDSYS, ...)
#                - APEX_*, ORDS_*, OJVM*, FLOWS_*, WK_* schemas
#                - Dictionary/dynamic-view prefixes (V$, GV$, DBA_, ALL_, ...)
#                - Customer-prefix namespace (default: empty) for DBUSER,
#                  OSUSER, SCHEMA and OBJECT
#                - 'n/a', 'UNKNOWN' placeholders set by NVL()
#                - oracle.com, localhost, localhost.localdomain
#
#              Limitation: SQL*Plus WRAP-continuation lines are not joined
#              before extraction. Values exceeding the column width may be
#              missed by the section pass but are usually caught by the
#              FQDN pattern in the global scan.
#
# Usage......: anonymize_audit_log.py INPUT [--output FILE] [--mapping FILE]
#                                     [--load-mapping FILE] [--whitelist FILE]
#                                     [--customer-prefix PREFIX]
#                                     [--dry-run] [--yes] [--verbose]
#
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# ------------------------------------------------------------------------------
# CHANGE LOG:
# 2026.05.28  oes  Sanitised port from audit_pack-0.5.0                   0.2.0
# ------------------------------------------------------------------------------

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

CATEGORIES = ("HOST", "IP", "DBUSER", "OSUSER", "CLIENT", "SCHEMA",
              "OBJECT", "EMAIL")

# Column-heading (lowercase, stripped) -> category.
# Matched against the heading line directly above each dashes line in
# SQL*Plus output. Headings that mean "count of distinct X" (e.g.
# "User (distinct)", "Programs (distinct)", "Actions (distinct)") are
# deliberately NOT mapped - their values are numbers, not identifiers.
HEADING_TO_CATEGORY = {
    # Hostnames
    "host":                "HOST",
    "host (distinct)":     "HOST",
    "user host":           "HOST",
    "userhost":            "HOST",
    "machine":             "HOST",
    # DB users
    "db user":             "DBUSER",
    "dbusername":          "DBUSER",
    "username":            "DBUSER",
    "user":                "DBUSER",
    # OS users
    "os user":             "OSUSER",
    "os_username":         "OSUSER",
    "osuser":              "OSUSER",
    # Client / program names
    "client program":      "CLIENT",
    "client program name": "CLIENT",
    "client_program_name": "CLIENT",
    "program":             "CLIENT",
    # Schemas
    "schema":              "SCHEMA",
    "object_schema":       "SCHEMA",
    # Object names
    "objects":             "OBJECT",
    "object":              "OBJECT",
    "object_name":         "OBJECT",
}

# Oracle-supplied DB users / schemas - never anonymise.
ORACLE_USERS = {
    "SYS", "SYSTEM", "DBSNMP", "DBSFWUSER", "OUTLN", "XS$NULL", "ANONYMOUS",
    "GSMADMIN_INTERNAL", "GSMCATUSER", "GSMUSER", "GSMROOTUSER", "GGSYS",
    "AUDSYS", "ORACLE_OCM", "REMOTE_SCHEDULER_AGENT", "DIP",
    "DVF", "DVSYS", "LBACSYS", "MDDATA",
    "XDB", "WMSYS", "CTXSYS", "ORDSYS", "ORDDATA", "ORDPLUGINS",
    "MDSYS", "OLAPSYS", "SI_INFORMTN_SCHEMA", "FLOWS_FILES",
    "APEX_PUBLIC_USER", "OJVMSYS", "SYS$UMF",
    "SYSBACKUP", "SYSDG", "SYSKM", "SYSRAC",
    "PUBLIC",
}

# Schema/user prefixes that mark Oracle-supplied / versioned namespaces.
ORACLE_SCHEMA_PREFIXES = ("APEX_", "ORDS_", "OJVM", "FLOWS_", "WK_")

# Object-name prefixes for Oracle-supplied dictionary / dynamic views.
ORACLE_OBJECT_PREFIXES = (
    "V$", "V_$", "GV$", "GV_$",
    "DBA_", "ALL_", "USER_", "CDB_",
    "X$", "ORA_", "AUDSYS$",
)
ORACLE_OBJECT_NAMES = {"DUAL"}

# Placeholders set by NVL() - keep readable.
PLACEHOLDER_VALUES = {"n/a", "N/A", "UNKNOWN", "(null)"}

# FQDN tokens that should NOT be anonymised (public references that may
# appear in audit data or doc strings).
FQDN_WHITELIST = {
    "oracle.com",
    "oradba.ch",
    "localhost",
    "localhost.localdomain",
}

# File extensions that look like FQDNs but aren't.
FILE_EXTENSIONS = {
    "sql", "log", "txt", "csv", "json", "xml", "html", "htm", "md",
    "yml", "yaml", "conf", "ini", "tmp", "bak", "pdf", "dmp", "lst",
    "out", "trc", "aud", "ora", "tab", "py", "sh",
}

# Local-parts that mark "tool@host" strings (NOT real email addresses).
TOOL_LOCAL_PARTS = {
    "sqlplus", "rman", "srvctl", "dgmgrl", "expdp", "impdp",
    "exp", "imp", "lsnrctl", "tnslsnr", "tnsping", "adrci",
    "oracle", "grid", "sqlcl", "sqlldr",
}

# Generic Oracle client program names - keep readable, they reveal no
# customer info and improve analyst readability.
CLIENT_WHITELIST = {
    "JDBC Thin Client", "SQL Developer", "sqlplus", "SQL*Plus",
    "sqlcl", "Toad.exe", "DataGrip", "PL/SQL Developer", "DBeaver",
    "MS Excel", "MS Access", "ODBC", "OCI",
}

# Patterns for the global pattern-based scan.
# Note: FQDN regex deliberately avoids variable-length lookaheads and
# unbounded backtracking - 7.5 MB inputs choked on the textbook pattern.
IPV4_RE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
FQDN_RE = re.compile(
    r"\b[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?"
    r"(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?){1,}\b"
)
EMAIL_RE = re.compile(
    r"\b[A-Za-z0-9._%+-]{1,64}@"
    r"[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?"
    r"(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?){1,}\b"
)

# SQL*Plus structural patterns.
DASHES_LINE_RE = re.compile(r"^-{3,}(\s+-{3,})*\s*$")
ROWS_SELECTED_RE = re.compile(
    r"^\s*\d+\s+rows?\s+selected\.?\s*$",
    re.IGNORECASE,
)

# Token-boundary class for substitution guards. Hostnames, identifiers
# and schema-qualified object names use [A-Za-z0-9_.\-$].
TOKEN_BOUNDARY = r"[A-Za-z0-9_.\-\$]"

# A "plain" key is one that consists only of token-class characters -
# these are eligible for fast O(N) token-scan substitution. Keys with
# spaces, '@', parentheses, etc. fall back to batched regex.
_PLAIN_KEY_RE = re.compile(r"^[A-Za-z0-9_.\-\$]+$")
_PLAIN_TOKEN_RE = re.compile(r"[A-Za-z0-9_.\-\$]+")


# ---------------------------------------------------------------------------
# Extraction
# ---------------------------------------------------------------------------

def _parse_column_spans(dashes_line):
    """Return list of (start, end) for each run of dashes."""
    spans = []
    start = None
    for i, ch in enumerate(dashes_line):
        if ch == "-":
            if start is None:
                start = i
        else:
            if start is not None:
                spans.append((start, i))
                start = None
    if start is not None:
        spans.append((start, len(dashes_line)))
    return spans


def _classify_columns(heading_line, spans):
    """Map each column span to a category (or None) based on the
    column-heading text directly above the dashes line."""
    classified = []
    for start, end in spans:
        heading = heading_line[start:end].strip().lower()
        category = HEADING_TO_CATEGORY.get(heading)
        classified.append((start, end, category))
    return classified


def extract_section_values(lines):
    """Harvest sensitive values from every result-set table in the file.

    Uses the column-heading line directly above each dashes line to
    decide which columns to extract. Works for both the full audit
    report and individual sub-scripts (e.g. aud_trail_userhost_analysis).

    Returns dict[category] = set(values).
    """
    collected = defaultdict(set)
    in_data = False
    columns = []      # list of (start, end, category_or_None)
    prev_line = ""

    for raw in lines:
        line = raw.rstrip("\n")

        if DASHES_LINE_RE.match(line):
            spans = _parse_column_spans(line)
            columns = _classify_columns(prev_line, spans)
            in_data = any(cat for _, _, cat in columns)
            prev_line = line
            continue

        if ROWS_SELECTED_RE.match(line):
            in_data = False
            columns = []
            prev_line = line
            continue

        # PROMPT lines, section separators "===", and decorative lines
        # break the current result set. Reset so the next dashes line
        # re-evaluates column structure.
        if line.lstrip().startswith("="):
            in_data = False
            columns = []
            prev_line = line
            continue

        # Blank lines do not reset data state - SQL*Plus emits them as
        # WRAP-row separators between long values that overflow their
        # column width. Resetting here would lose the next legitimate
        # data row.
        if not line.strip():
            prev_line = line
            continue

        if in_data and columns:
            first_start, first_end, _ = columns[0]
            first_val = line[first_start:first_end].strip()

            # Skip wrap-continuation lines: content only in column 1,
            # all other columns empty. Happens when a value exceeds its
            # column width (A60 etc.); the overflow chars appear on a
            # new line at column 1.
            if first_val and len(columns) > 1:
                has_other_cols = any(
                    line[s:e].strip() for s, e, _ in columns[1:]
                )
                if not has_other_cols:
                    prev_line = line
                    continue

            # Skip recurring heading rows. SQL*Plus re-emits the heading
            # + dashes pair on every page break (PAGESIZE). Without this,
            # the literal heading word ("Host", "DB User", ...) gets
            # harvested as a value.
            if first_val.lower() in HEADING_TO_CATEGORY:
                prev_line = line
                continue

            for start, end, cat in columns:
                if cat is None:
                    continue
                value = line[start:end].strip()
                if not value or value in PLACEHOLDER_VALUES:
                    continue
                if cat == "CLIENT" and "@" in value:
                    after = value.split("@", 1)[1].split()[0]
                    if after:
                        collected["HOST"].add(after)
                    continue
                collected[cat].add(value)

        prev_line = line

    return collected


def extract_patterns(text):
    """Whole-file scan for IPv4 addresses, FQDNs, email addresses."""
    ips = set(IPV4_RE.findall(text))
    fqdns_raw = set(FQDN_RE.findall(text))

    # IPv4 also matches the FQDN regex - keep them in IP only.
    fqdns_raw -= ips

    # Drop file-name-like tokens (foo.sql, bar.log, ...).
    fqdns = {
        f for f in fqdns_raw
        if f.rsplit(".", 1)[-1].lower() not in FILE_EXTENSIONS
    }

    # Drop "tool@host" pseudo-emails (sqlplus@host, rman@host, ...).
    emails_raw = set(EMAIL_RE.findall(text))
    emails = {
        e for e in emails_raw
        if e.split("@", 1)[0].lower() not in TOOL_LOCAL_PARTS
    }
    # An email's host part is in the FQDN set - move it to EMAIL only.
    for e in emails:
        host = e.split("@", 1)[1]
        fqdns.discard(host)

    return ips, fqdns, emails


# ---------------------------------------------------------------------------
# Whitelist
# ---------------------------------------------------------------------------

def is_ambiguous(value, category):
    """Return True if a value would be unsafe to substitute globally
    because it would collide with non-sensitive tokens elsewhere in
    the file. Examples:
      - '30' in "(last 30 days)" or login counts
      - '001', '-10' from K8s StatefulSet ordinals
      - '2', 'A2' from column-boundary spillover

    Purely-numeric / very-short values cannot be safely masked without
    structural column awareness, which the current parser does not
    provide. IP addresses and email addresses are exempt because they
    are validated by stricter patterns."""
    if category in ("IP", "EMAIL"):
        return False
    if len(value) < 3:
        return True
    if not any(c.isalpha() for c in value):
        return True
    return False


def is_whitelisted(value, category, customer_prefix, extra_whitelist):
    """Return True if value should NOT be anonymised."""
    if value in PLACEHOLDER_VALUES:
        return True
    if value in extra_whitelist:
        return True

    upper = value.upper()
    lower = value.lower()

    if category in ("DBUSER", "OSUSER", "SCHEMA"):
        if upper in ORACLE_USERS:
            return True
        if any(upper.startswith(p) for p in ORACLE_SCHEMA_PREFIXES):
            return True

    if category == "OBJECT":
        if upper in ORACLE_OBJECT_NAMES:
            return True
        if any(upper.startswith(p) for p in ORACLE_OBJECT_PREFIXES):
            return True

    if customer_prefix and category in ("DBUSER", "OSUSER", "SCHEMA", "OBJECT"):
        if upper == customer_prefix or upper.startswith(customer_prefix + "_"):
            return True

    if category in ("HOST", "IP"):
        if lower in FQDN_WHITELIST:
            return True

    if category == "CLIENT" and value in CLIENT_WHITELIST:
        return True

    return False


# ---------------------------------------------------------------------------
# Mapping
# ---------------------------------------------------------------------------

def build_mapping(collected, customer_prefix, extra_whitelist, existing=None):
    """Assign deterministic pseudonyms.

    Returns:
        mapping: dict[original_value] = pseudonym
        stats:   dict[category] = (kept, anonymised)
    """
    mapping = dict(existing or {})

    # Reserve indices already used by an existing mapping.
    used_indices = defaultdict(set)
    for pseudo in mapping.values():
        if "_" in pseudo:
            cat, idx = pseudo.rsplit("_", 1)
            if idx.isdigit():
                used_indices[cat].add(int(idx))

    stats = {}
    ambiguous_samples = defaultdict(list)
    for category in CATEGORIES:
        values = sorted(collected.get(category, set()))
        kept = 0
        anonymised = 0
        ambiguous = 0
        for value in values:
            if value in mapping:
                continue
            if is_ambiguous(value, category):
                ambiguous += 1
                if len(ambiguous_samples[category]) < 5:
                    ambiguous_samples[category].append(value)
                continue
            if is_whitelisted(value, category, customer_prefix,
                              extra_whitelist):
                kept += 1
                continue
            idx = 1
            while idx in used_indices[category]:
                idx += 1
            used_indices[category].add(idx)
            mapping[value] = f"{category}_{idx:03d}"
            anonymised += 1
        stats[category] = (kept, anonymised, ambiguous)

    return mapping, stats, dict(ambiguous_samples)


# ---------------------------------------------------------------------------
# Substitution
# ---------------------------------------------------------------------------

_BATCH_SIZE = 500


def apply_substitution(text, mapping):
    """Replace every mapped original value with its pseudonym.

    Two passes for performance on large inputs (tested: 7.5 MB / 18k
    mappings runs in seconds, not minutes):

      Pass 1 (multi-token keys) - keys containing spaces, '@', etc.
        These are few. Batched alternation regex with token-boundary
        guards. Longest-first ordering avoids partial overlaps.

      Pass 2 (plain identifier keys) - keys made entirely of
        [A-Za-z0-9_.\\-$]. These are thousands. A single O(N) token
        scan with dict lookup: the token regex extracts maximal
        identifier runs and looks each up in the plain-key dict.
    """
    if not mapping:
        return text

    plain = {}
    multi = {}
    for k, v in mapping.items():
        if _PLAIN_KEY_RE.match(k):
            plain[k] = v
        else:
            multi[k] = v

    if multi:
        keys_sorted = sorted(multi.keys(), key=len, reverse=True)
        for start in range(0, len(keys_sorted), _BATCH_SIZE):
            batch = keys_sorted[start:start + _BATCH_SIZE]
            pattern = re.compile(
                rf"(?<!{TOKEN_BOUNDARY})("
                + "|".join(re.escape(k) for k in batch)
                + rf")(?!{TOKEN_BOUNDARY})"
            )
            text = pattern.sub(lambda m: multi[m.group(1)], text)

    if plain:
        text = _PLAIN_TOKEN_RE.sub(
            lambda m: plain.get(m.group(0), m.group(0)),
            text,
        )

    return text


# ---------------------------------------------------------------------------
# Mapping persistence
# ---------------------------------------------------------------------------

def load_mapping_file(path: Path):
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("mapping", {})


def save_mapping_file(path: Path, mapping, meta):
    payload = {
        "meta": meta,
        "mapping": dict(sorted(mapping.items())),
    }
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv):
    p = argparse.ArgumentParser(
        prog="anonymize_audit_log.py",
        description=(
            "Pseudonymise sensitive values (hostnames, IPs, DB/OS users, "
            "client programs, schemas, object names, emails) in Oracle "
            "Unified Audit spool files produced by aud_report_full_aud.sql."
        ),
        epilog=(
            "Default outputs live next to INPUT:\n"
            "  <INPUT>.anon.log         anonymised log\n"
            "  <INPUT>.mapping.json     reverse-lookup table (KEEP LOCAL)\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("input", type=Path,
                   help="Path to the spool log file.")
    p.add_argument("--output", type=Path,
                   help="Anonymised output path "
                        "(default: <INPUT>.anon.log next to input).")
    p.add_argument("--mapping", type=Path,
                   help="Mapping output path "
                        "(default: <INPUT>.mapping.json next to input).")
    p.add_argument("--load-mapping", type=Path,
                   help="Pre-load an existing mapping JSON for "
                        "incremental anonymisation across multiple logs.")
    p.add_argument("--whitelist", type=Path,
                   help="Optional JSON file with a 'whitelist' array of "
                        "additional values to keep visible.")
    p.add_argument("--customer-prefix", default="",
                   help="Schema / object / user prefix to keep visible "
                        "(customer-specific namespace). "
                        "Default: empty (no namespace prefix). "
                        "Pass an explicit value to protect your prefix.")
    p.add_argument("--dry-run", action="store_true",
                   help="Report stats only, do not write any files.")
    p.add_argument("--yes", "-y", action="store_true",
                   help="Overwrite existing outputs without prompting.")
    p.add_argument("--verbose", "-v", action="store_true",
                   help="Print sample mappings per category.")
    return p.parse_args(argv)


def _confirm_overwrite(path: Path, assume_yes: bool) -> bool:
    if not path.exists() or assume_yes:
        return True
    answer = input(f"Overwrite {path}? [y/N] ").strip().lower()
    return answer == "y"


def _derive_output_path(inp: Path, kind: str) -> Path:
    """Build '<input-stem>.<kind>' but keep the original extension chain."""
    if kind == "anon":
        return inp.with_name(inp.stem + ".anon" + inp.suffix)
    if kind == "mapping":
        return inp.with_name(inp.stem + ".mapping.json")
    raise ValueError(kind)


def main(argv=None):
    args = parse_args(argv)

    inp: Path = args.input
    if not inp.is_file():
        print(f"ERROR: input file not found: {inp}", file=sys.stderr)
        return 2

    out_path = args.output or _derive_output_path(inp, "anon")
    map_path = args.mapping or _derive_output_path(inp, "mapping")

    customer_prefix = (args.customer_prefix or "").upper()

    extra_whitelist = set()
    if args.whitelist:
        if not args.whitelist.is_file():
            print(f"ERROR: whitelist file not found: {args.whitelist}",
                  file=sys.stderr)
            return 2
        data = json.loads(args.whitelist.read_text(encoding="utf-8"))
        extra_whitelist = set(data.get("whitelist", []))

    existing_mapping = {}
    if args.load_mapping:
        existing_mapping = load_mapping_file(args.load_mapping)

    # utf-8-sig strips an optional BOM that SQL*Plus sometimes emits.
    text = inp.read_text(encoding="utf-8-sig", errors="replace")
    lines = text.splitlines(keepends=True)

    collected = extract_section_values(lines)
    ips, fqdns, emails = extract_patterns(text)

    # IPs in the userhost section should be classified as IP, not HOST.
    ip_in_host = collected.get("HOST", set()) & ips
    collected["HOST"] -= ip_in_host
    collected["IP"] |= ip_in_host

    # Pattern-based finds: only add to HOST/IP/EMAIL if the value is not
    # already claimed by a section-aware category. This prevents user
    # names like "john.doe" (matched by FQDN regex) from getting a HOST
    # pseudonym when they were correctly extracted as DBUSER.
    already = set().union(*collected.values())
    collected["IP"] |= (ips - already)
    already |= collected["IP"]
    collected["HOST"] |= (fqdns - already)
    already |= collected["HOST"]
    collected["EMAIL"] |= (emails - already)

    mapping, stats, ambiguous_samples = build_mapping(
        collected, customer_prefix, extra_whitelist,
        existing=existing_mapping,
    )

    # Skip the substitution pass when --dry-run is set; it can be the
    # slowest part on large inputs and dry-run only needs the stats.
    anon_text = None if args.dry_run else apply_substitution(text, mapping)

    # --- Report ----------------------------------------------------------
    print(f"Input:           {inp}  ({inp.stat().st_size:,} bytes)")
    print(f"Output:          {out_path}")
    print(f"Mapping:         {map_path}")
    print(f"Customer prefix: {customer_prefix or '(disabled)'}")
    if existing_mapping:
        print(f"Loaded mapping:  {args.load_mapping} "
              f"({len(existing_mapping)} entries)")
    print()
    print(f"{'Category':<10} {'kept':>8} {'anonymised':>12} {'ambiguous':>11}")
    print(f"{'-' * 10} {'-' * 8} {'-' * 12} {'-' * 11}")
    total_kept = 0
    total_anon = 0
    total_amb = 0
    for cat in CATEGORIES:
        k, a, amb = stats.get(cat, (0, 0, 0))
        print(f"{cat:<10} {k:>8} {a:>12} {amb:>11}")
        total_kept += k
        total_anon += a
        total_amb += amb
    print(f"{'-' * 10} {'-' * 8} {'-' * 12} {'-' * 11}")
    print(f"{'TOTAL':<10} {total_kept:>8} {total_anon:>12} {total_amb:>11}")
    if total_amb:
        print(f"\n(ambiguous = numeric-only or too-short values left "
              f"unchanged because they would collide with non-sensitive "
              f"tokens elsewhere in the file)")
        if args.verbose:
            for cat, samples in ambiguous_samples.items():
                if samples:
                    print(f"  [{cat}] sample ambiguous values: "
                          + ", ".join(repr(s) for s in samples))

    if args.verbose:
        for cat in CATEGORIES:
            samples = sorted(
                k for k, v in mapping.items() if v.startswith(cat + "_")
            )[:5]
            if samples:
                print(f"\n[{cat}] sample mappings:")
                for s in samples:
                    print(f"  {s!r} -> {mapping[s]}")

    if args.dry_run:
        print("\n(dry-run: no files written)")
        return 0

    if not _confirm_overwrite(out_path, args.yes):
        print("Aborted.", file=sys.stderr)
        return 1
    if not _confirm_overwrite(map_path, args.yes):
        print("Aborted.", file=sys.stderr)
        return 1

    if anon_text is None:
        anon_text = apply_substitution(text, mapping)
    out_path.write_text(anon_text, encoding="utf-8")

    meta = {
        "source": str(inp),
        "categories": list(CATEGORIES),
        "customer_prefix_kept": customer_prefix,
        "total_mappings": len(mapping),
    }
    save_mapping_file(map_path, mapping, meta)

    print(f"\nWrote anonymised log -> {out_path}")
    print(f"Wrote mapping        -> {map_path}")
    print("\nReminder: the mapping file contains real values. KEEP LOCAL.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
