-- SPDX-License-Identifier: Apache-2.0
-- -----------------------------------------------------------------------------
-- OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
-- -----------------------------------------------------------------------------
-- Name......: 22-crit-pkg-executions.sql
-- Author....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
-- Date......: 2026.07.08
-- Revision..: 0.1.0
-- Purpose...: Audit trail events for the 19 CIS Benchmark 5.1.3 critical
--             SYS packages (ODB_LOC_CRIT_PKG_V2 scope). Surface which users
--             executed which security-critical package, from which host, and
--             how often - the primary data for CIS 5.3 compliance evidence.
--
--             Critical package list (CIS Oracle DB Benchmark 5.1.3):
--               DBMS_AW, DBMS_CRYPTO, DBMS_FGA, DBMS_JAVA_TEST, DBMS_JOB,
--               DBMS_LOGMNR, DBMS_NETWORK_ACL_ADMIN, DBMS_OBFUSCATION_TOOLKIT,
--               DBMS_REDACT, DBMS_REDEFINITION, DBMS_RLS, DBMS_SCHEDULER,
--               DBMS_SQL_TRANSLATOR, DBMS_SYS_SQL, DBMS_TSDP_MANAGE,
--               DBMS_TSDP_PROTECT, DBMS_XMLGEN, DBMS_XMLSTORE, OWA_UTIL
--
--             The query filters on OBJECT_SCHEMA = 'SYS' and OBJECT_NAME in
--             the package list; ACTION_NAME = 'EXECUTE'. This works regardless
--             of whether the events were generated by ODB_LOC_CRIT_PKG_V2 or
--             the ORA$MANDATORY policy (DBMS_FGA, DBMS_AUDIT_MGMT).
--
-- Pattern...: Multi-dimension aggregate: package x user x host.
-- Notes.....: Requires SELECT on UNIFIED_AUDIT_TRAIL (AUDIT_VIEWER or
--             AUDIT_ADMIN). DBMS_FGA and DBMS_AUDIT_MGMT events also appear
--             here even when ODB_LOC_CRIT_PKG_V2 is not deployed (covered
--             by ORA$MANDATORY). A result set with only DBMS_FGA + AUDIT_MGMT
--             entries may indicate the package policy is not yet enabled.
-- License...: Apache License Version 2.0
-- -----------------------------------------------------------------------------

SPOOL &LOGDIR./22_crit_pkg_executions.csv

PROMPT # query: crit_pkg_executions
PROMPT # query_id: 22
PROMPT # dbsid: &DBSID
PROMPT # pdb: &PDB_NAME
PROMPT # generated: &GENERATED_ISO
PROMPT # cis_controls: 5.3
PROMPT # date_range_days: &days
PROMPT # top_n: &top_n
PROMPT # schema: object_name=KEEP|dbusername=PSEUDO:DBUSER|userhost=PSEUDO:HOST|client_program_name=PSEUDO:CLIENT|return_code=KEEP|executions=COUNT|distinct_hosts=COUNT|first_seen=TIMESTAMP|last_seen=TIMESTAMP

SET MARKUP CSV ON DELIMITER '|' QUOTE OFF

SELECT
    NVL(object_name, '(null)')                                       AS "object_name",
    NVL(dbusername, '(null)')                                        AS "dbusername",
    NVL(userhost, '(null)')                                          AS "userhost",
    NVL(client_program_name, '(null)')                               AS "client_program_name",
    NVL(TO_CHAR(return_code), '0')                                   AS "return_code",
    COUNT(*)                                                         AS "executions",
    COUNT(DISTINCT userhost)                                         AS "distinct_hosts",
    TO_CHAR(MIN(event_timestamp_utc), 'YYYY-MM-DD HH24:MI:SS')       AS "first_seen",
    TO_CHAR(MAX(event_timestamp_utc), 'YYYY-MM-DD HH24:MI:SS')       AS "last_seen"
FROM unified_audit_trail
WHERE event_timestamp_utc >= SYSTIMESTAMP - NUMTODSINTERVAL(TO_NUMBER('&days'), 'DAY')
  AND dbid = con_id_to_dbid(SYS_CONTEXT('USERENV','CON_ID'))
  AND action_name = 'EXECUTE'
  AND object_schema = 'SYS'
  AND object_name IN (
        'DBMS_AW',
        'DBMS_CRYPTO',
        'DBMS_FGA',
        'DBMS_JAVA_TEST',
        'DBMS_JOB',
        'DBMS_LOGMNR',
        'DBMS_NETWORK_ACL_ADMIN',
        'DBMS_OBFUSCATION_TOOLKIT',
        'DBMS_REDACT',
        'DBMS_REDEFINITION',
        'DBMS_RLS',
        'DBMS_SCHEDULER',
        'DBMS_SQL_TRANSLATOR',
        'DBMS_SYS_SQL',
        'DBMS_TSDP_MANAGE',
        'DBMS_TSDP_PROTECT',
        'DBMS_XMLGEN',
        'DBMS_XMLSTORE',
        'OWA_UTIL'
      )
GROUP BY
    NVL(object_name, '(null)'),
    NVL(dbusername, '(null)'),
    NVL(userhost, '(null)'),
    NVL(client_program_name, '(null)'),
    NVL(TO_CHAR(return_code), '0')
ORDER BY executions DESC
FETCH FIRST TO_NUMBER('&top_n') ROWS ONLY;

SET MARKUP CSV OFF
SPOOL OFF
